name: Tests

on:
  push:
  pull_request:

env:
  BROWSER_STACK_ACCESS_KEY: "${{ secrets.BROWSER_STACK_ACCESS_KEY }}"
  BROWSER_STACK_USERNAME: "${{ secrets.BROWSER_STACK_USERNAME }}"

jobs:
  test:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12, 14, 16, 18, 20]
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test

  test-targets:
    name: ${{ matrix.targets.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets:
          - name: "Lint"
            target: "lint"
          - name: "Documentation"
            target: "test-docs"
          - name: "Jest"
            target: "test-jest"
          - name: "Browser - IE11"
            target: "test-browser-ie11"
          - name: "Chrome Headless"
            target: "test-headless"

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "12"
      - run: npm install
      - run: npm run ${{ matrix.targets.target }}
